#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  sym_newline = 7,
  sym_indent = 8,
  sym_dedent = 9,
  sym_string_start = 10,
  sym_string_content = 11,
  sym_string_end = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym_line = 15,
  sym_scope = 16,
  sym__curl_scope = 17,
  sym__paren_scope = 18,
  sym__bracket_scope = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_line_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_newline] = "newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_string_start] = "string_start",
  [sym_string_content] = "string_content",
  [sym_string_end] = "string_end",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_scope] = "scope",
  [sym__curl_scope] = "_curl_scope",
  [sym__paren_scope] = "_paren_scope",
  [sym__bracket_scope] = "_bracket_scope",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_newline] = sym_newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_string_start] = sym_string_start,
  [sym_string_content] = sym_string_content,
  [sym_string_end] = sym_string_end,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_scope] = sym_scope,
  [sym__curl_scope] = sym__curl_scope,
  [sym__paren_scope] = sym__paren_scope,
  [sym__bracket_scope] = sym__bracket_scope,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_string_start] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_end] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__curl_scope] = {
    .visible = false,
    .named = true,
  },
  [sym__paren_scope] = {
    .visible = false,
    .named = true,
  },
  [sym__bracket_scope] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 3,
  [10] = 2,
  [11] = 4,
  [12] = 6,
  [13] = 13,
  [14] = 5,
  [15] = 2,
  [16] = 16,
  [17] = 16,
  [18] = 16,
  [19] = 5,
  [20] = 3,
  [21] = 13,
  [22] = 6,
  [23] = 4,
  [24] = 13,
  [25] = 16,
  [26] = 3,
  [27] = 5,
  [28] = 13,
  [29] = 4,
  [30] = 2,
  [31] = 31,
  [32] = 32,
  [33] = 31,
  [34] = 32,
  [35] = 32,
  [36] = 31,
  [37] = 31,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 40,
  [44] = 40,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 45,
  [49] = 46,
  [50] = 47,
  [51] = 39,
  [52] = 41,
  [53] = 42,
  [54] = 46,
  [55] = 45,
  [56] = 40,
  [57] = 42,
  [58] = 41,
  [59] = 39,
  [60] = 47,
  [61] = 47,
  [62] = 46,
  [63] = 45,
  [64] = 39,
  [65] = 42,
  [66] = 41,
  [67] = 67,
  [68] = 67,
  [69] = 67,
  [70] = 67,
  [71] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == '[') ADVANCE(6);
      if (lookahead == ']') ADVANCE(7);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 4},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 4},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 4},
  [21] = {.lex_state = 0, .external_lex_state = 4},
  [22] = {.lex_state = 0, .external_lex_state = 4},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 4},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 4},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 5},
  [32] = {.lex_state = 0, .external_lex_state = 5},
  [33] = {.lex_state = 0, .external_lex_state = 6},
  [34] = {.lex_state = 0, .external_lex_state = 7},
  [35] = {.lex_state = 0, .external_lex_state = 8},
  [36] = {.lex_state = 0, .external_lex_state = 8},
  [37] = {.lex_state = 0, .external_lex_state = 7},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 0, .external_lex_state = 7},
  [40] = {.lex_state = 0, .external_lex_state = 5},
  [41] = {.lex_state = 0, .external_lex_state = 6},
  [42] = {.lex_state = 0, .external_lex_state = 6},
  [43] = {.lex_state = 0, .external_lex_state = 8},
  [44] = {.lex_state = 0, .external_lex_state = 7},
  [45] = {.lex_state = 0, .external_lex_state = 8},
  [46] = {.lex_state = 0, .external_lex_state = 8},
  [47] = {.lex_state = 0, .external_lex_state = 8},
  [48] = {.lex_state = 0, .external_lex_state = 7},
  [49] = {.lex_state = 0, .external_lex_state = 7},
  [50] = {.lex_state = 0, .external_lex_state = 6},
  [51] = {.lex_state = 0, .external_lex_state = 8},
  [52] = {.lex_state = 0, .external_lex_state = 8},
  [53] = {.lex_state = 0, .external_lex_state = 8},
  [54] = {.lex_state = 0, .external_lex_state = 6},
  [55] = {.lex_state = 0, .external_lex_state = 6},
  [56] = {.lex_state = 0, .external_lex_state = 6},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0, .external_lex_state = 7},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 5},
  [63] = {.lex_state = 0, .external_lex_state = 5},
  [64] = {.lex_state = 0, .external_lex_state = 6},
  [65] = {.lex_state = 0, .external_lex_state = 7},
  [66] = {.lex_state = 0, .external_lex_state = 7},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 3},
  [70] = {.lex_state = 0, .external_lex_state = 4},
  [71] = {.lex_state = 0},
};

enum {
  ts_external_token_newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
  ts_external_token_string_start = 3,
  ts_external_token_string_content = 4,
  ts_external_token_string_end = 5,
  ts_external_token_comment = 6,
  ts_external_token_RBRACK = 7,
  ts_external_token_RPAREN = 8,
  ts_external_token_RBRACE = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_newline] = sym_newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_string_start] = sym_string_start,
  [ts_external_token_string_content] = sym_string_content,
  [ts_external_token_string_end] = sym_string_end,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_RBRACK] = anon_sym_RBRACK,
  [ts_external_token_RPAREN] = anon_sym_RPAREN,
  [ts_external_token_RBRACE] = anon_sym_RBRACE,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_string_start] = true,
    [ts_external_token_string_content] = true,
    [ts_external_token_string_end] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_RBRACK] = true,
    [ts_external_token_RPAREN] = true,
    [ts_external_token_RBRACE] = true,
  },
  [2] = {
    [ts_external_token_RBRACE] = true,
  },
  [3] = {
    [ts_external_token_RBRACK] = true,
  },
  [4] = {
    [ts_external_token_RPAREN] = true,
  },
  [5] = {
    [ts_external_token_newline] = true,
    [ts_external_token_RBRACE] = true,
  },
  [6] = {
    [ts_external_token_newline] = true,
    [ts_external_token_RPAREN] = true,
  },
  [7] = {
    [ts_external_token_newline] = true,
  },
  [8] = {
    [ts_external_token_newline] = true,
    [ts_external_token_RBRACK] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_string_start] = ACTIONS(1),
    [sym_string_content] = ACTIONS(1),
    [sym_string_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(71),
    [sym_line] = STATE(7),
    [sym_scope] = STATE(37),
    [sym__curl_scope] = STATE(44),
    [sym__paren_scope] = STATE(44),
    [sym__bracket_scope] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_line_repeat1] = STATE(37),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(26), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [26] = 7,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(24), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    STATE(3), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(37), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(44), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [52] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(36), 1,
      anon_sym_RBRACK,
    STATE(14), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [78] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(38), 1,
      anon_sym_RBRACK,
    STATE(9), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [104] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(44), 1,
      anon_sym_RPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    STATE(20), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [130] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(37), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(44), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [156] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    STATE(20), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [182] = 7,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    STATE(9), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [208] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [234] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    STATE(5), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [260] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    STATE(20), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [286] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(6), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [312] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
    STATE(9), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [338] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [364] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [390] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [416] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(10), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [442] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 1,
      anon_sym_RBRACK,
    STATE(9), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [468] = 7,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(81), 1,
      anon_sym_LBRACE,
    ACTIONS(84), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    STATE(20), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [494] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(12), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [520] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    STATE(20), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [546] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      anon_sym_RBRACK,
    STATE(19), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [572] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    STATE(8), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [598] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [624] = 7,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(106), 1,
      anon_sym_LBRACK,
    STATE(26), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [650] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(9), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [676] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(22), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(33), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [702] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_RBRACK,
    STATE(27), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(36), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [728] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_line,
      aux_sym_source_file_repeat1,
    STATE(31), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [754] = 7,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      sym_newline,
    STATE(32), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [779] = 6,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(126), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 2,
      sym_newline,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(40), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [802] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(132), 1,
      sym_newline,
    STATE(38), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [827] = 6,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(140), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 2,
      sym_newline,
      ts_builtin_sym_end,
    STATE(34), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(44), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [850] = 6,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    ACTIONS(146), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 2,
      sym_newline,
      anon_sym_RBRACK,
    STATE(35), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [873] = 7,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    ACTIONS(152), 1,
      sym_newline,
    STATE(35), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(43), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [898] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 1,
      sym_newline,
    STATE(34), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(44), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [923] = 6,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 2,
      sym_newline,
      anon_sym_RPAREN,
    STATE(38), 2,
      sym_scope,
      aux_sym_line_repeat1,
    STATE(56), 3,
      sym__curl_scope,
      sym__paren_scope,
      sym__bracket_scope,
  [946] = 1,
    ACTIONS(165), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [954] = 1,
    ACTIONS(167), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [962] = 1,
    ACTIONS(169), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [970] = 1,
    ACTIONS(171), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [978] = 1,
    ACTIONS(167), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [986] = 1,
    ACTIONS(167), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [994] = 1,
    ACTIONS(173), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1002] = 1,
    ACTIONS(175), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1010] = 1,
    ACTIONS(177), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1018] = 1,
    ACTIONS(173), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1026] = 1,
    ACTIONS(175), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1034] = 1,
    ACTIONS(177), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [1042] = 1,
    ACTIONS(165), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1050] = 1,
    ACTIONS(169), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1058] = 1,
    ACTIONS(171), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1066] = 1,
    ACTIONS(175), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [1074] = 1,
    ACTIONS(173), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [1082] = 1,
    ACTIONS(167), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [1090] = 1,
    ACTIONS(171), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1098] = 1,
    ACTIONS(169), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1106] = 1,
    ACTIONS(165), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1114] = 1,
    ACTIONS(177), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1122] = 1,
    ACTIONS(177), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1130] = 1,
    ACTIONS(175), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1138] = 1,
    ACTIONS(173), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1146] = 1,
    ACTIONS(165), 5,
      sym_newline,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [1154] = 1,
    ACTIONS(171), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1162] = 1,
    ACTIONS(169), 5,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1170] = 1,
    ACTIONS(179), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1177] = 1,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1184] = 1,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1191] = 1,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [1198] = 1,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 208,
  [SMALL_STATE(11)] = 234,
  [SMALL_STATE(12)] = 260,
  [SMALL_STATE(13)] = 286,
  [SMALL_STATE(14)] = 312,
  [SMALL_STATE(15)] = 338,
  [SMALL_STATE(16)] = 364,
  [SMALL_STATE(17)] = 390,
  [SMALL_STATE(18)] = 416,
  [SMALL_STATE(19)] = 442,
  [SMALL_STATE(20)] = 468,
  [SMALL_STATE(21)] = 494,
  [SMALL_STATE(22)] = 520,
  [SMALL_STATE(23)] = 546,
  [SMALL_STATE(24)] = 572,
  [SMALL_STATE(25)] = 598,
  [SMALL_STATE(26)] = 624,
  [SMALL_STATE(27)] = 650,
  [SMALL_STATE(28)] = 676,
  [SMALL_STATE(29)] = 702,
  [SMALL_STATE(30)] = 728,
  [SMALL_STATE(31)] = 754,
  [SMALL_STATE(32)] = 779,
  [SMALL_STATE(33)] = 802,
  [SMALL_STATE(34)] = 827,
  [SMALL_STATE(35)] = 850,
  [SMALL_STATE(36)] = 873,
  [SMALL_STATE(37)] = 898,
  [SMALL_STATE(38)] = 923,
  [SMALL_STATE(39)] = 946,
  [SMALL_STATE(40)] = 954,
  [SMALL_STATE(41)] = 962,
  [SMALL_STATE(42)] = 970,
  [SMALL_STATE(43)] = 978,
  [SMALL_STATE(44)] = 986,
  [SMALL_STATE(45)] = 994,
  [SMALL_STATE(46)] = 1002,
  [SMALL_STATE(47)] = 1010,
  [SMALL_STATE(48)] = 1018,
  [SMALL_STATE(49)] = 1026,
  [SMALL_STATE(50)] = 1034,
  [SMALL_STATE(51)] = 1042,
  [SMALL_STATE(52)] = 1050,
  [SMALL_STATE(53)] = 1058,
  [SMALL_STATE(54)] = 1066,
  [SMALL_STATE(55)] = 1074,
  [SMALL_STATE(56)] = 1082,
  [SMALL_STATE(57)] = 1090,
  [SMALL_STATE(58)] = 1098,
  [SMALL_STATE(59)] = 1106,
  [SMALL_STATE(60)] = 1114,
  [SMALL_STATE(61)] = 1122,
  [SMALL_STATE(62)] = 1130,
  [SMALL_STATE(63)] = 1138,
  [SMALL_STATE(64)] = 1146,
  [SMALL_STATE(65)] = 1154,
  [SMALL_STATE(66)] = 1162,
  [SMALL_STATE(67)] = 1170,
  [SMALL_STATE(68)] = 1177,
  [SMALL_STATE(69)] = 1184,
  [SMALL_STATE(70)] = 1191,
  [SMALL_STATE(71)] = 1198,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(16),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(24),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(17),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(17),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(28),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(29),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(18),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(21),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(4),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(16),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(13),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(11),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(25),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(24),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2), SHIFT_REPEAT(23),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__curl_scope, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paren_scope, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bracket_scope, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__curl_scope, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paren_scope, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bracket_scope, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2),
  [181] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_scope_external_scanner_create(void);
void tree_sitter_scope_external_scanner_destroy(void *);
bool tree_sitter_scope_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_scope_external_scanner_serialize(void *, char *);
void tree_sitter_scope_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_scope(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_scope_external_scanner_create,
      tree_sitter_scope_external_scanner_destroy,
      tree_sitter_scope_external_scanner_scan,
      tree_sitter_scope_external_scanner_serialize,
      tree_sitter_scope_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
